"""
generate_notebook.py — Generate analysis.ipynb with the full RegimeShift pipeline.

Run: cd regime-shift && python notebooks/generate_notebook.py
"""

from __future__ import annotations

import json
import os

NOTEBOOK_PATH = os.path.join(os.path.dirname(__file__), "analysis.ipynb")


def build_cells() -> list:
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# RegimeShift — Full Analysis\n",
                "\n",
                "Student-t HMM for adaptive portfolio allocation across\n",
                "equity, gold, and bond regimes.\n",
                "\n",
                "**Pipeline:**\n",
                "1. Load price data\n",
                "2. Compute 54 regime features\n",
                "3. Fit Student-t HMM (3 regimes)\n",
                "4. Walk-forward backtest with transaction costs\n",
                "5. Compare to benchmarks (60/40, EqualWeight, Buy&Hold)\n",
                "6. Analyze regime-specific performance\n",
                "7. Visualize everything\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import sys\n",
                "sys.path.insert(0, 'src')\n",
                "\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import logging\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "logging.basicConfig(level=logging.INFO)\n",
                "# plt.style.use('seaborn-v0_8-whitegrid')\n",
                "\n",
                "from regime_shift.data_loader import compute_returns, compute_features\n",
                "from regime_shift.regime_detector import RegimeDetector\n",
                "from regime_shift.optimizer import PortfolioOptimizer\n",
                "from regime_shift.transaction_costs import TransactionCostModel\n",
                "from regime_shift.backtest import WalkForwardBacktest, BacktestResult\n",
                "from regime_shift.benchmarks import run_benchmarks\n",
                "from regime_shift.evaluate import (\n",
                "    compute_metrics, compute_regime_metrics, compute_turnover_metrics,\n",
                "    bootstrap_metrics,\n",
                ")\n",
                "from regime_shift.visualize import (\n",
                "    plot_regime_timeline, plot_cumulative_returns, plot_drawdown,\n",
                "    plot_rolling_sharpe, plot_monthly_heatmap, plot_regime_weights,\n",
                "    plot_regime_performance, plot_turnover_costs, plot_regime_transitions,\n",
                "    plot_feature_correlations, save_all_plots,\n",
                ")\n",
                "\n",
                "print(\"All imports successful\")\n",
                "%matplotlib inline",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 1: Load Data (Simulated)\n",
                "# ──────────────────────────────────────────────\n",
                "from regime_shift.data_loader import _simulate_prices\n",
                "\n",
                "prices = _simulate_prices()\n",
                "returns = compute_returns(prices)\n",
                "features = compute_features(returns, tickers=prices.columns.tolist(), window=20)\n",
                "features = features.dropna()\n",
                "\n",
                "print(f\"Prices shape:    {prices.shape}\")\n",
                "print(f\"Returns shape:   {returns.shape}\")\n",
                "print(f\"Features shape:  {features.shape}\")\n",
                "\n",
                "prices.head()\n",
                "features.head()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 2: Fit HMM and Detect Regimes\n",
                "# ──────────────────────────────────────────────\n",
                "detector = RegimeDetector(n_states=3, lookback=252, retrain_freq=21)\n",
                "regime_series = detector.fit_predict(features)\n",
                "\n",
                "print(\"\\nRegime distribution:\")\n",
                "print(regime_series.value_counts())\n",
                "\n",
                "print(f\"\\nSilhouette score: {detector.silhouette_score:.3f}\")\n",
                "\n",
                "trans = detector.get_transition_matrix()\n",
                "if trans is not None:\n",
                "    diag = np.diag(trans)\n",
                "    durations = 1.0 / (1.0 - diag)\n",
                "    print(f\"Expected regime durations: {durations.round(1)}\")\n",
                "\n",
                "metrics = detector.get_regime_metrics()\n",
                "print(f\"\\nEM iterations: {metrics.get('n_iter', 'N/A')}\")\n",
                "print(f\"Log-likelihood: {metrics.get('log_likelihood', 0):.2f}\")\n",
                "\n",
                "regime_series.head(10)",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 3: Visualize Regimes\n",
                "# ──────────────────────────────────────────────\n",
                "fig, ax = plot_regime_timeline(regime_series, prices=prices)\n",
                "plt.show()\n",
                "\n",
                "# Plot transition matrix\n",
                "trans = detector.get_transition_matrix()\n",
                "if trans is not None:\n",
                "    plot_regime_transitions(trans)",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 4: Walk-Forward Backtest\n",
                "# ──────────────────────────────────────────────\n",
                "cost_model = TransactionCostModel()\n",
                "optimizer = PortfolioOptimizer(n_assets=len(returns.columns))\n",
                "\n",
                "bt = WalkForwardBacktest(\n",
                "    prices=prices,\n",
                "    returns=returns,\n",
                "    features=features,\n",
                "    lookback=252,\n",
                "    retrain_freq=21,\n",
                "    cost_model=cost_model,\n",
                ")\n",
                "result = bt.run()\n",
                "\n",
                "print(f\"\\nBacktest complete: {len(result.portfolio_returns)} days, \"\n",
                "      f\"{result.regime_changes} regime changes\")\n",
                "print(f\"Sharpe: {result.sharpe_ratio:.2f}, \"\n",
                "      f\"Total Return: {result.total_return:.1%}, \"\n",
                "      f\"Max DD: {result.max_drawdown:.1%}\")",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 5: Performance Metrics\n",
                "# ──────────────────────────────────────────────\n",
                "strat_metrics = compute_metrics(result.portfolio_returns, name=\"RegimeShift\")\n",
                "regime_m = compute_regime_metrics(result.portfolio_returns, result.regime_series)\n",
                "turnover_m = compute_turnover_metrics(result.weights_history, result.regime_series)\n",
                "\n",
                "print(f\"\\n{'=' * 50}\")\n",
                "print(f\"  REGIMESHIFT RESULTS\")\n",
                "print(f\"{'=' * 50}\")\n",
                "print(f\"  Total Return:      {strat_metrics.total_return:.1%}\")\n",
                "print(f\"  Ann. Return:       {strat_metrics.annualized_return:.1%}\")\n",
                "print(f\"  Ann. Volatility:   {strat_metrics.annualized_volatility:.1%}\")\n",
                "print(f\"  Sharpe Ratio:      {strat_metrics.sharpe_ratio:.2f}\")\n",
                "print(f\"  Max Drawdown:      {strat_metrics.max_drawdown:.1%}\")\n",
                "print(f\"  Win Rate:          {strat_metrics.win_rate:.1%}\")\n",
                "\n",
                "print(f\"\\n--- Regime Breakdown ---\")\n",
                "if len(regime_m) > 0:\n",
                "    print(regime_m.to_string())\n",
                "\n",
                "print(f\"\\n--- Turnover ---\")\n",
                "print(f\"  Avg daily turnover:  {turnover_m['avg_daily_turnover']:.4f}\")\n",
                "print(f\"  Avg annual turnover: {turnover_m['avg_annual_turnover']:.1f}x\")",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 6: Benchmarks\n",
                "# ──────────────────────────────────────────────\n",
                "bench_results = run_benchmarks(\n",
                "    prices, returns, features,\n",
                "    cost_model=cost_model,\n",
                "    rebalance_freq=21,\n",
                "    lookback=252,\n",
                ")\n",
                "\n",
                "for name, br in bench_results.items():\n",
                "    m = compute_metrics(br.portfolio_returns, name=name)\n",
                "    print(f\"{name:<15} Sharpe={m.sharpe_ratio:6.2f}  \"\n",
                "          f\"Return={m.total_return:8.1%}  MaxDD={m.max_drawdown:8.1%}\")",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 7: Visualizations\n",
                "# ──────────────────────────────────────────────\n",
                "fig, ax = plot_cumulative_returns(\n",
                "    result.portfolio_returns,\n",
                "    {n: br.portfolio_returns for n, br in bench_results.items()},\n",
                "    regime_series=result.regime_series,\n",
                ")\n",
                "plt.show()\n",
                "\n",
                "fig, ax = plot_drawdown(result.portfolio_returns)\n",
                "plt.show()\n",
                "\n",
                "fig, ax = plot_rolling_sharpe(result.portfolio_returns)\n",
                "plt.show()\n",
                "\n",
                "fig, ax = plot_regime_performance(regime_m)\n",
                "plt.show()\n",
                "\n",
                "fig, ax = plot_monthly_heatmap(result.portfolio_returns)\n",
                "plt.show()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 8: Feature Analysis\n",
                "# ──────────────────────────────────────────────\n",
                "fig, ax = plot_feature_correlations(features, max_features=30)\n",
                "plt.show()\n",
                "\n",
                "# Feature importance via between-regime t-statistics\n",
                "from regime_shift.regime_detector import RegimeLabeler\n",
                "\n",
                "labeler = RegimeLabeler(n_states=3)\n",
                "X = features.values\n",
                "states = detector._viterbi(X)\n",
                "labeler.fit(X, states)\n",
                "\n",
                "# Compute |t-stat| for each feature between Bull vs Bear\n",
                "bull_mask = states == labeler.label_to_idx[\"Bull\"]\n",
                "bear_mask = states == labeler.label_to_idx[\"Bear\"]\n",
                "\n",
                "t_stats = []\n",
                "for col_idx in range(X.shape[1]):\n",
                "    bull_vals = X[bull_mask, col_idx]\n",
                "    bear_vals = X[bear_mask, col_idx]\n",
                "    n1, n2 = len(bull_vals), len(bear_vals)\n",
                "    if n1 < 2 or n2 < 2:\n",
                "        t_stats.append(0.0)\n",
                "        continue\n",
                "    m1, m2 = bull_vals.mean(), bear_vals.mean()  \n",
                "    s1, s2 = bull_vals.std(ddof=1), bear_vals.std(ddof=1)\n",
                "    pooled_se = np.sqrt(s1**2/n1 + s2**2/n2)\n",
                "    t_stat = abs(m1 - m2) / (pooled_se + 1e-12)\n",
                "    t_stats.append(t_stat)\n",
                "\n",
                "t_stats = np.array(t_stats)\n",
                "feature_names = features.columns.tolist()\n",
                "\n",
                "fig, ax = plot_feature_importance(feature_names, t_stats, top_n=20)\n",
                "plt.show()",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 9: Bootstrap Confidence Intervals\n",
                "# ──────────────────────────────────────────────\n",
                "from regime_shift.evaluate import bootstrap_metrics\n",
                "\n",
                "ci = bootstrap_metrics(result.portfolio_returns, n_bootstrap=500, block_size=21)\n",
                "\n",
                "if ci:\n",
                "    print(\"Bootstrap Confidence Intervals (500 draws, 21-day blocks):\")\n",
                "    for metric, (med, lo, hi) in ci.items():\n",
                "        print(f\"  {metric}: {med:.3f} [{lo:.3f}, {hi:.3f}]\")",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# ──────────────────────────────────────────────\n",
                "# STEP 10: Export Results\n",
                "# ──────────────────────────────────────────────\n",
                "import os\n",
                "os.makedirs(\"results\", exist_ok=True)\n",
                "\n",
                "result.portfolio_returns.to_csv(\"results/portfolio_returns.csv\")\n",
                "result.weights_history.to_csv(\"results/weights_history.csv\")\n",
                "result.regime_series.to_csv(\"results/regime_series.csv\")\n",
                "result.costs.to_csv(\"results/transaction_costs.csv\")\n",
                "\n",
                "save_all_plots(\n",
                "    result, bench_results, regime_m, turnover_m,\n",
                "    features=features, output_dir=\"results\",\n",
                ")\n",
                "\n",
                "print(\"Results exported to results/\")\n",
                "print(\"  - portfolio_returns.csv\")\n",
                "print(\"  - weights_history.csv\")\n",
                "print(\"  - regime_series.csv\")\n",
                "print(\"  - transaction_costs.csv\")\n",
                "print(\"  - 8 PNG plots in results/\")",
            ],
        },
    ]
    return cells


def create_notebook() -> None:
    """Create analysis.ipynb from cell definitions."""
    nb = {
        "cells": build_cells(),
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }

    with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)

    print(f"Created {NOTEBOOK_PATH}")


if __name__ == "__main__":
    create_notebook()
